#! /usr/bin/zsh

# start from root
cd /home/reed

# turn off spaceship-prompt git section
sed -i '/^  git           # Git section (git_branch + git_status)$/s/^/#/' .zshrc

# reinitialize zsh
source .zshrc
